name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        elixir: [1.8.x, 1.9.x, 1.10.x]
        otp: [20.x, 21.x, 22.x]
        exclude:
          - elixir: 1.10.x
            otp: 20.x

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - name: Install Dependencies
        run: mix deps.get --only test
      - name: Run Tests
        run: mix test
