name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        pair:
          - elixir: 1.7.4
            otp: 19.x
          - elixir: 1.8.x
            otp: 20.x
          - elixir: 1.9.x
            otp: 21.x
          - elixir: 1.10.x
            otp: 22.x
          - elixir: 1.10.x
            otp: 23.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.pair.elixir}}
          otp-version: ${{matrix.pair.otp}}
      - name: Install Dependencies
        run: mix deps.get --only test
      - name: Run Tests
        run: mix test
