name: CI

on: [push, pull_request]

jobs:
  format:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.4
          otp-version: 23.0.4
      - mix deps.get
      - mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      matrix:
        pair:
          - elixir: 1.7.4
            otp: 19.x
          - elixir: 1.8.x
            otp: 20.x
          - elixir: 1.9.x
            otp: 21.x
          - elixir: 1.10.x
            otp: 22.x
          - elixir: 1.10.x
            otp: 23.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.pair.elixir}}
          otp-version: ${{matrix.pair.otp}}
      - mix deps.get
      - mix test
